import type { ApiError } from './client';

export type ProcessingErrorSource = 'pdf' | 'conversion' | 'unknown';

const ERROR_CODE_KEYS: Readonly<Record<string, string>> = {
  INVALID_REQUEST: 'invalidRequest',
  INVALID_ARGUMENT: 'invalidArgument',
  INVALID_JSON: 'invalidJson',
  CONFLICTING_ARGUMENTS: 'conflictingArguments',
  INVALID_FILE_TYPE: 'invalidFileType',
  FILE_REQUIRED: 'fileRequired',
  FILE_COUNT_MISMATCH: 'fileCountMismatch',
  FILE_TOO_LARGE: 'fileTooLargeAsync',
  PAGE_LIMIT_EXCEEDED: 'pageLimitExceeded',
  INVALID_OUTPUT_FILE_NAME: 'invalidOutputFileName',
  INVALID_PAGE_RANGE: 'invalidPageRange',
  INVALID_PAGE_INDEX: 'invalidPageIndex',
  INVALID_RECT: 'invalidRect',
  INVALID_QUAD_RECTS: 'invalidRect',
  PAGE_RANGE_EMPTY: 'pageRangeEmpty',
  PASSWORD_REQUIRED: 'passwordRequired',
  INVALID_PASSWORD: 'invalidPassword',
  CERTIFICATE_INVALID: 'certificateInvalid',
  CERTIFICATE_PASSWORD_REQUIRED: 'certificatePasswordRequired',
  CERTIFICATE_PASSWORD_INVALID: 'certificatePasswordInvalid',
  TRUSTED_CERTIFICATE_INVALID: 'certificateInvalid',
  ICC_PROFILE_REQUIRED: 'iccProfileRequired',
  ICC_PROFILE_INVALID: 'iccProfileRequired',
  UNSUPPORTED_OPERATION: 'unsupportedOperation',
  UNSUPPORTED_ENUM_VALUE: 'unsupportedEnumValue',
  SIGNATURE_NOT_FOUND: 'signatureNotFound',
  WATERMARK_NOT_FOUND: 'watermarkNotFound',
  BACKGROUND_NOT_FOUND: 'backgroundNotFound',
  HEADER_FOOTER_NOT_FOUND: 'headerFooterNotFound',
  BATES_NOT_FOUND: 'batesNotFound',
  REDACTION_NOT_FOUND: 'redactionNotFound',
  NO_CHANGES_DETECTED: 'noChangesDetected',
  SDK_PROCESS_FAILED: 'processFailed',
  TEMP_FILE_WRITE_FAILED: 'tempFileWriteFailed',
  TEMP_FILE_READ_FAILED: 'tempFileReadFailed',
  RESULT_PACKAGE_FAILED: 'resultPackageFailed',
  RESOURCE_EXHAUSTED: 'resourceExhausted',
  REQUEST_TIMEOUT: 'requestTimeout',
  AUTH_REQUIRED: 'authRequired',
  UNAUTHORIZED: 'authInvalid',
  FORBIDDEN: 'permissionDenied',
  INVALID_TOKEN: 'invalidToken',
  NOT_FOUND: 'notFound',
  JOB_NOT_READY: 'jobNotReady',
  INVALID_STATE: 'invalidState',
  IDEMPOTENCY_IN_PROGRESS: 'idempotencyInProgress',
  CONVERSION_FAILED: 'convertFailed',
  CONVERT_FAILED: 'convertFailed',
  PDF_PASSWORD_ERROR: 'pdfPasswordError',
  PDF_FORMAT_ERROR: 'pdfFormatError',
  PDF_SECURITY_ERROR: 'pdfSecurityError',
  OCR_FAILURE: 'ocrFailure',
  JOB_TIMEOUT: 'jobTimeout',
  SYNC_WAIT_TIMEOUT: 'jobTimeout',
  NO_TABLE: 'noTable',
  OUT_OF_MEMORY: 'outOfMemory',
  SDK_FILE_ERROR: 'fileError',
  IMAGE_INVALID: 'imageInvalid',
  INTERNAL_ERROR: 'internalError',
  UPSTREAM_ERROR: 'processFailed',
  BAD_REQUEST: 'invalidRequest',
  VALIDATION_ERROR: 'paramValidation',
  CONFLICT: 'invalidState',
  CONCURRENCY_LIMIT: 'concurrencyExceeded',
  CONCURRENCY_EXCEEDED: 'concurrencyExceeded',
  LICENSE_EXPIRED: 'licenseExpired',
  LICENSE_INVALID: 'licenseInvalid',
  LICENSE_MISSING: 'licenseMissing',
};

const SHARED_NUMERIC_KEYS: Readonly<Record<number, string>> = {
  100001: 'invalidRequest',
  100002: 'invalidJson',
  100003: 'conflictingArguments',
  100101: 'invalidFileType',
  100102: 'fileRequired',
  100103: 'fileCountMismatch',
  100104: 'fileTooLargeAsync',
  100105: 'pageLimitExceeded',
  100106: 'invalidOutputFileName',
  110001: 'invalidPageRange',
  110002: 'invalidPageIndex',
  110003: 'invalidRect',
  110004: 'invalidRect',
  110005: 'pageRangeEmpty',
};

const PDF_NUMERIC_KEYS: Readonly<Record<number, string>> = {
  ...SHARED_NUMERIC_KEYS,
  120001: 'passwordRequired',
  120002: 'invalidPassword',
  120101: 'certificateInvalid',
  120102: 'certificatePasswordRequired',
  120103: 'certificatePasswordInvalid',
  120104: 'certificateInvalid',
  120201: 'iccProfileRequired',
  120202: 'iccProfileRequired',
  130001: 'unsupportedOperation',
  130002: 'unsupportedEnumValue',
  130101: 'signatureNotFound',
  130102: 'watermarkNotFound',
  130103: 'backgroundNotFound',
  130104: 'headerFooterNotFound',
  130105: 'batesNotFound',
  130106: 'redactionNotFound',
  130107: 'noChangesDetected',
  130011: 'licenseExpired',
  130012: 'concurrencyExceeded',
  190001: 'processFailed',
  190002: 'tempFileWriteFailed',
  190003: 'tempFileReadFailed',
  190004: 'resultPackageFailed',
  190005: 'resourceExhausted',
  190006: 'requestTimeout',
  190999: 'internalError',
};

const CONVERSION_NUMERIC_KEYS: Readonly<Record<number, string>> = {
  ...SHARED_NUMERIC_KEYS,
  120001: 'authRequired',
  120002: 'invalidToken',
  130001: 'notFound',
  130002: 'jobNotReady',
  130003: 'invalidState',
  130004: 'idempotencyInProgress',
  190001: 'convertFailed',
  190002: 'pdfPasswordError',
  190003: 'pdfFormatError',
  190004: 'pdfSecurityError',
  190005: 'ocrFailure',
  190006: 'jobTimeout',
  190007: 'noTable',
  190008: 'outOfMemory',
  190009: 'fileError',
  190010: 'imageInvalid',
  190999: 'internalError',
};

export function apiErrorTranslationKey(
  error: Pick<ApiError, 'code' | 'errorCode' | 'message'>,
  source: ProcessingErrorSource = 'unknown',
): string | null {
  if (error.errorCode && ERROR_CODE_KEYS[error.errorCode]) {
    return ERROR_CODE_KEYS[error.errorCode];
  }
  if (typeof error.code !== 'number') return null;
  if (source === 'pdf') return PDF_NUMERIC_KEYS[error.code] ?? null;
  if (source === 'conversion') return CONVERSION_NUMERIC_KEYS[error.code] ?? null;
  return SHARED_NUMERIC_KEYS[error.code]
    ?? PDF_NUMERIC_KEYS[error.code]
    ?? CONVERSION_NUMERIC_KEYS[error.code]
    ?? null;
}
