export interface ProcessingErrorDefinition {
  errorCode: string;
  message: string;
}

export type ProcessingErrorCatalog = Readonly<Record<number, ProcessingErrorDefinition>>;

export const CONVERSION_ERROR_CATALOG: ProcessingErrorCatalog = {
  0: { errorCode: 'SUCCESS', message: 'Success, and no error occurs.' },
  1: { errorCode: 'CANCEL', message: 'Conversion process was canceled.' },
  2: { errorCode: 'FILE_ERROR', message: 'File cannot be found or could not be opened.' },
  3: { errorCode: 'PDF_PASSWORD_ERROR', message: 'Invalid password. Usually, this error may occur when loading a PDF document with password.' },
  4: { errorCode: 'PDF_PAGE_ERROR', message: 'PDF page failed to load.' },
  5: { errorCode: 'PDF_FORMAT_ERROR', message: 'Format is invalid. For files, this may also mean that file is corrupted.' },
  6: { errorCode: 'PDF_SECURITY_ERROR', message: 'PDF document is encrypted by some unsupported security handler.' },
  7: { errorCode: 'OUT_OF_MEMORY', message: 'Out-of-memory error occurs.' },
  8: { errorCode: 'IO_ERROR', message: 'System I/O error.' },
  9: { errorCode: 'COMPRESS_ERROR', message: 'Folder compression failed.' },
  20: { errorCode: 'LICENSE_INVALID', message: 'The license is invalid.' },
  21: { errorCode: 'LICENSE_EXPIRE', message: 'The license has expired.' },
  22: { errorCode: 'LICENSE_UNSUPPORTED_PLATFORM', message: 'The license does not support the current platform.' },
  23: { errorCode: 'LICENSE_UNSUPPORTED_ID', message: 'The license does not support the application ID.' },
  24: { errorCode: 'LICENSE_UNSUPPORTED_DEVICE', message: 'The license does not support the device ID.' },
  25: { errorCode: 'LICENSE_PERMISSION_DENY', message: 'The license does not have the function permission.' },
  26: { errorCode: 'LICENSE_UNINITIALIZED', message: 'The license has not been initialized.' },
  27: { errorCode: 'LICENSE_ILLEGAL_ACCESS', message: 'Illegal access to the API interface.' },
  28: { errorCode: 'LICENSE_FILE_READ_FAILED', message: 'Failed to read the license file.' },
  29: { errorCode: 'LICENSE_OCR_PERMISSION_DENY', message: 'The license does not have OCR permissions.' },
  30: { errorCode: 'LICENSE_CONCURRENCY_EXCEEDED', message: 'The current conversion concurrency exceeds the license limit.' },
  31: { errorCode: 'LICENSE_PAGE_LIMIT_EXCEEDED', message: 'The current conversion pages exceed the license limit.' },
  32: { errorCode: 'LICENSE_QUOTA_CORRUPTED', message: 'The quota persistence file has been tampered with.' },
  40: { errorCode: 'NO_TABLE_ERROR', message: 'No tables found in the source file.' },
  41: { errorCode: 'OCR_FAILURE', message: 'Failed to call OCR recognition.' },
  60: { errorCode: 'CONVERTING_ERROR', message: 'A conversion task is currently executing.' },
  80: { errorCode: 'INVALID_ARG', message: 'Invalid argument provided.' },
  81: { errorCode: 'INVALID_HANDLE', message: 'The handle is invalid, possibly uninitialized or already released.' },
  82: { errorCode: 'INVALID_MODEL_FORMAT', message: 'The model file format is invalid or corrupted.' },
  83: { errorCode: 'MODEL_FUNCTION_UNSUPPORTED', message: 'The model does not support the requested function or operation.' },
  84: { errorCode: 'MODEL_FORMAT_UNSUPPORTED', message: 'The model format is not supported by this system or SDK.' },
  85: { errorCode: 'MODEL_SDK_MISMATCH', message: 'The model is incompatible with the current SDK version.' },
  86: { errorCode: 'IMAGE_DATA_EMPTY', message: 'The image data is empty or not provided.' },
  87: { errorCode: 'IMAGE_WIDTH_HEIGHT_ERROR', message: 'The image width or height is invalid.' },
  88: { errorCode: 'IMAGE_FORMAT_UNSUPPORTED', message: 'The image format is not supported.' },
  89: { errorCode: 'IMAGE_INVALID', message: 'The image is invalid or corrupted.' },
  90: { errorCode: 'EXPIRE_ERROR', message: 'The resource has expired.' },
  91: { errorCode: 'MISSING_ARG', message: 'A required argument is missing.' },
  92: { errorCode: 'LICENSE_UNSUPPORTED_API', message: 'The current license does not support calling this API.' },
  93: { errorCode: 'LICENSE_MISMATCH', message: 'The license does not match the device, module, or version.' },
  94: { errorCode: 'INVALID_TABLE', message: 'The table data is invalid or null.' },
  100: { errorCode: 'UNKNOWN_ERROR', message: 'Unknown error.' },
  100001: { errorCode: 'INVALID_REQUEST', message: 'Missing or invalid request parameters.' },
  100101: { errorCode: 'INVALID_FILE_TYPE', message: 'The uploaded file type is not supported.' },
  100104: { errorCode: 'FILE_TOO_LARGE', message: 'The file exceeds the service size limit.' },
  100105: { errorCode: 'PAGE_LIMIT_EXCEEDED', message: 'The PDF page count exceeds the service limit.' },
  120001: { errorCode: 'AUTH_REQUIRED', message: 'The authorization header is missing or invalid.' },
  120002: { errorCode: 'INVALID_TOKEN', message: 'The token is invalid or expired.' },
  130001: { errorCode: 'NOT_FOUND', message: 'The requested resource or result file was not found.' },
  130002: { errorCode: 'JOB_NOT_READY', message: 'The task has not succeeded yet.' },
  130003: { errorCode: 'INVALID_STATE', message: 'The current task state does not allow this operation.' },
  130004: { errorCode: 'IDEMPOTENCY_IN_PROGRESS', message: 'A request with the same idempotency key is in progress.' },
  190001: { errorCode: 'CONVERT_FAILED', message: 'Document conversion failed.' },
  190002: { errorCode: 'PDF_PASSWORD_ERROR', message: 'The PDF password is incorrect or missing.' },
  190003: { errorCode: 'PDF_FORMAT_ERROR', message: 'The PDF format is invalid or the file is corrupted.' },
  190004: { errorCode: 'PDF_SECURITY_ERROR', message: 'The PDF uses an unsupported security handler.' },
  190005: { errorCode: 'OCR_FAILURE', message: 'OCR recognition failed.' },
  190006: { errorCode: 'JOB_TIMEOUT', message: 'Document conversion timed out.' },
  190007: { errorCode: 'NO_TABLE', message: 'No table was found in the source file.' },
  190008: { errorCode: 'OUT_OF_MEMORY', message: 'The conversion service ran out of memory.' },
  190009: { errorCode: 'SDK_FILE_ERROR', message: 'The file could not be opened or was not found.' },
  190010: { errorCode: 'IMAGE_INVALID', message: 'The image is invalid, corrupted, or unsupported.' },
  190999: { errorCode: 'INTERNAL_ERROR', message: 'The conversion service encountered an internal error.' },
};

export const PDF_ERROR_CATALOG: ProcessingErrorCatalog = {
  100001: { errorCode: 'INVALID_ARGUMENT', message: 'A required argument is missing, has an invalid type, or contains an unsupported value.' },
  100002: { errorCode: 'INVALID_JSON', message: 'The request JSON could not be parsed.' },
  100003: { errorCode: 'CONFLICTING_ARGUMENTS', message: 'Mutually exclusive arguments were provided together.' },
  100101: { errorCode: 'INVALID_FILE_TYPE', message: 'The uploaded file type does not meet the operation requirements.' },
  100102: { errorCode: 'FILE_REQUIRED', message: 'A required file field is missing.' },
  100103: { errorCode: 'FILE_COUNT_MISMATCH', message: 'The file count does not match the related parameter array.' },
  100104: { errorCode: 'FILE_TOO_LARGE', message: 'The file exceeds the service size limit.' },
  100105: { errorCode: 'PAGE_LIMIT_EXCEEDED', message: 'The PDF page count exceeds the service limit.' },
  100106: { errorCode: 'INVALID_OUTPUT_FILE_NAME', message: 'The output file name is invalid.' },
  110001: { errorCode: 'INVALID_PAGE_RANGE', message: 'The page range is invalid or outside the document bounds.' },
  110002: { errorCode: 'INVALID_PAGE_INDEX', message: 'The page index is invalid or outside the document bounds.' },
  110003: { errorCode: 'INVALID_RECT', message: 'The rectangle coordinates are invalid.' },
  110004: { errorCode: 'INVALID_QUAD_RECTS', message: 'One or more quadrilateral regions are invalid.' },
  110005: { errorCode: 'PAGE_RANGE_EMPTY', message: 'The page range contains no pages to process.' },
  120001: { errorCode: 'PASSWORD_REQUIRED', message: 'The document is encrypted but no password was provided.' },
  120002: { errorCode: 'INVALID_PASSWORD', message: 'The PDF password is incorrect.' },
  120101: { errorCode: 'CERTIFICATE_INVALID', message: 'The certificate file is invalid or uses an unsupported format.' },
  120102: { errorCode: 'CERTIFICATE_PASSWORD_REQUIRED', message: 'The certificate requires a password.' },
  120103: { errorCode: 'CERTIFICATE_PASSWORD_INVALID', message: 'The certificate password is incorrect.' },
  120104: { errorCode: 'TRUSTED_CERTIFICATE_INVALID', message: 'The trusted certificate or certificate chain is invalid.' },
  120201: { errorCode: 'ICC_PROFILE_REQUIRED', message: 'An ICC profile is required for this standards conversion.' },
  120202: { errorCode: 'ICC_PROFILE_INVALID', message: 'The ICC profile is invalid or incompatible with the target standard.' },
  130001: { errorCode: 'UNSUPPORTED_OPERATION', message: 'The current document or SDK does not support this operation.' },
  130002: { errorCode: 'UNSUPPORTED_ENUM_VALUE', message: 'The enum value is outside the allowed range.' },
  130101: { errorCode: 'SIGNATURE_NOT_FOUND', message: 'The specified signature was not found.' },
  130102: { errorCode: 'WATERMARK_NOT_FOUND', message: 'The specified watermark was not found.' },
  130103: { errorCode: 'BACKGROUND_NOT_FOUND', message: 'No editable background was found in the document.' },
  130104: { errorCode: 'HEADER_FOOTER_NOT_FOUND', message: 'No header or footer configuration was found in the document.' },
  130105: { errorCode: 'BATES_NOT_FOUND', message: 'No Bates numbering was found in the document.' },
  130106: { errorCode: 'REDACTION_NOT_FOUND', message: 'No applicable redaction marks were found.' },
  130107: { errorCode: 'NO_CHANGES_DETECTED', message: 'The operation completed but produced no changes.' },
  190001: { errorCode: 'SDK_PROCESS_FAILED', message: 'PDF SDK processing failed.' },
  190002: { errorCode: 'TEMP_FILE_WRITE_FAILED', message: 'Failed to write a temporary file.' },
  190003: { errorCode: 'TEMP_FILE_READ_FAILED', message: 'Failed to read a temporary or SDK output file.' },
  190004: { errorCode: 'RESULT_PACKAGE_FAILED', message: 'Failed to package multiple result files.' },
  190005: { errorCode: 'RESOURCE_EXHAUSTED', message: 'The PDF service does not have enough resources to process the request.' },
  190006: { errorCode: 'REQUEST_TIMEOUT', message: 'The PDF processing request timed out.' },
  190999: { errorCode: 'INTERNAL_ERROR', message: 'The PDF service encountered an internal error.' },
};

export function processingErrorDefinition(
  source: 'conversion' | 'pdf',
  code: number,
): ProcessingErrorDefinition | undefined {
  return source === 'conversion' ? CONVERSION_ERROR_CATALOG[code] : PDF_ERROR_CATALOG[code];
}
